# Generated by Django 6.0.3 on 2026-03-20 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quizz", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="opcao",
            options={"verbose_name": "Opção", "verbose_name_plural": "Opções"},
        ),
        migrations.AlterModelOptions(
            name="pergunta",
            options={"verbose_name": "Pergunta", "verbose_name_plural": "Perguntas"},
        ),
    ]
