# Generated by Django 6.0.3 on 2026-04-10 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Festival",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("local", models.CharField(max_length=200)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField()),
                ("descricao", models.TextField(blank=True)),
                ("genero_musical", models.CharField(blank=True, max_length=100)),
                (
                    "preco_bilhete",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("url", models.URLField(blank=True)),
            ],
            options={
                "verbose_name": "Festival",
                "verbose_name_plural": "Festivais",
                "ordering": ["data_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Artista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("genero", models.CharField(blank=True, max_length=100)),
                ("pais_origem", models.CharField(blank=True, max_length=100)),
                (
                    "festivais",
                    models.ManyToManyField(
                        blank=True, related_name="artistas", to="festivais.festival"
                    ),
                ),
            ],
        ),
    ]
