# Generated by Django 6.0.4 on 2026-04-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escola_online", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="numero",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="curso",
            name="imagem",
            field=models.ImageField(default="", upload_to="cursos/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="professor",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
