# Generated by Django 6.0.3 on 2026-03-20 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ginasio", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sessao",
            options={"verbose_name": "Sessão", "verbose_name_plural": "Sessões"},
        ),
    ]
