# Generated by Django 6.0.3 on 2026-04-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("sigla", models.CharField(max_length=20)),
                ("instituicao", models.CharField(max_length=200)),
                ("ano_inicio", models.IntegerField()),
                ("duracao_anos", models.IntegerField()),
                ("url_pagina", models.URLField(blank=True)),
            ],
        ),
    ]
