# Generated by Django 6.0.3 on 2026-04-10 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Docente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("url_pagina_lusofona", models.URLField(blank=True)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="docentes/"),
                ),
            ],
        ),
    ]
