# Generated by Django 6.0.4 on 2026-04-11 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_unidadecurricular"),
    ]

    operations = [
        migrations.CreateModel(
            name="Interesse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("TEC", "Tecnologia"),
                            ("NEG", "Negócio"),
                            ("CIE", "Ciência"),
                            ("CUL", "Cultura"),
                            ("DES", "Desporto"),
                            ("OUT", "Outro"),
                        ],
                        default="TEC",
                        max_length=3,
                    ),
                ),
                ("url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("data", models.DateField(auto_now_add=True)),
                ("descricao", models.TextField()),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="makingof/"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("DER", "Diagrama DER"),
                            ("DEC", "Decisão de Modelação"),
                            ("ERR", "Erro e Correção"),
                            ("JUS", "Justificação"),
                            ("EVO", "Evolução do Modelo"),
                            ("IA", "Uso de IA"),
                        ],
                        default="JUS",
                        max_length=3,
                    ),
                ),
                (
                    "entidade_relacionada",
                    models.CharField(
                        blank=True,
                        help_text="Nome da entidade que este registo documenta",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "ordering": ["-data"],
            },
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="tecnologias/"),
                ),
                ("url_oficial", models.URLField(blank=True)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("LG", "Linguagem"),
                            ("FW", "Framework"),
                            ("BD", "Base de Dados"),
                            ("FE", "Ferramenta"),
                            ("SO", "Outro"),
                        ],
                        default="LG",
                        max_length=2,
                    ),
                ),
                (
                    "nivel_interesse",
                    models.IntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        default=3,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descricao", models.TextField()),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField(blank=True, null=True)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="projetos/"),
                ),
                ("url_github", models.URLField(blank=True)),
                ("url_demo", models.URLField(blank=True)),
                (
                    "conceitos_uc",
                    models.TextField(blank=True, help_text="Conceitos aplicados da UC"),
                ),
                (
                    "uc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projetos",
                        to="portfolio.unidadecurricular",
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(blank=True, to="portfolio.tecnologia"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("instituicao", models.CharField(max_length=200)),
                ("data_inicio", models.DateField()),
                ("data_conclusao", models.DateField(blank=True, null=True)),
                (
                    "certificado",
                    models.FileField(blank=True, null=True, upload_to="certificados/"),
                ),
                ("url", models.URLField(blank=True)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("CU", "Curso"),
                            ("CE", "Certificação"),
                            ("WO", "Workshop"),
                            ("AC", "Académico"),
                        ],
                        default="CU",
                        max_length=2,
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(blank=True, to="portfolio.tecnologia"),
                ),
            ],
            options={
                "ordering": ["-data_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("B", "Básico"),
                            ("I", "Intermédio"),
                            ("A", "Avançado"),
                        ],
                        default="B",
                        max_length=1,
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("T", "Técnica"), ("S", "Soft Skill")],
                        default="T",
                        max_length=1,
                    ),
                ),
                (
                    "projetos",
                    models.ManyToManyField(blank=True, to="portfolio.projeto"),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(blank=True, to="portfolio.tecnologia"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=300)),
                ("autor", models.CharField(max_length=200)),
                ("orientador", models.CharField(blank=True, max_length=200)),
                ("ano", models.IntegerField()),
                ("resumo", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
                ("area", models.CharField(blank=True, max_length=200)),
                ("destacado", models.BooleanField(default=False)),
                (
                    "tecnologias",
                    models.ManyToManyField(blank=True, to="portfolio.tecnologia"),
                ),
            ],
        ),
    ]
