# Generated by Django 6.0.4 on 2026-04-11 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_interesse_makingof_tecnologia_projeto_formacao_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="makingof",
            name="projeto",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="makingof_entries",
                to="portfolio.projeto",
            ),
        ),
        migrations.AddField(
            model_name="makingof",
            name="uc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="makingof_entries",
                to="portfolio.unidadecurricular",
            ),
        ),
        migrations.AlterField(
            model_name="makingof",
            name="entidade_relacionada",
            field=models.CharField(
                blank=True,
                help_text="Nome genérico da entidade (ex: Tecnologia, TFC)",
                max_length=100,
            ),
        ),
    ]
