# Generated by Django 6.0.4 on 2026-04-25 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_makingof_projeto_makingof_uc_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoTecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="Ex: Frontend, Backend, Base de Dados, Storage, Outros",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="tecnologia",
            name="categoria",
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="descricao",
            field=models.TextField(
                blank=True,
                help_text="O que faz, o que permite e aspetos que gostou ou não gostou.",
            ),
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="tipo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tecnologias",
                to="portfolio.tipotecnologia",
            ),
        ),
    ]
